[build]
  # Build command to install dependencies and build the frontend
  command = "npm run build"
  # The directory that contains the built site
  publish = "frontend/dist"
  # Directory to look for the package.json for dependency installation
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 